version: '3.8'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"


# version: '3.8'
# services:
#   mongo:
#     image: mongo
#     ports:
#       - "27017:27017"
#   backend:
#     build: ./backend
#     volumes:
#       - ./backend:/app
#     ports:
#       - "5000:5000"
#     depends_on:
#       - mongo
